services:
  client:
    build:
      context: ./bitcoin-moon/client
      dockerfile: Dockerfile
    container_name: moonbit-client
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "3000:3000"
    depends_on:
      - server
    restart: unless-stopped

  server:
    build:
      context: ./bitcoin-moon/server
      dockerfile: Dockerfile
    container_name: moonbit-server
    environment:
      - NODE_ENV=production
      - PORT=3001
      # Эти переменные используются для работы с внешними API
      # Можно указать фиктивные значения для запуска
      - COINGECKO_API_KEY=dummy_key
      - FARMSENSE_API_KEY=dummy_key
      - CORS_ORIGIN=http://localhost:3000
    ports:
      - "3001:3001"
    volumes:
      - ./bitcoin-moon/server/logs:/app/logs
    restart: unless-stopped 